---
- name: "Create Tiller Serviceaccount"
  shell: "export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf; kubectl -n kube-system create serviceaccount tiller"
  ignore_errors: yes
  become: yes

- name: "Bind Tiller Serviceaccount"
  shell: "export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf; kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller"
  ignore_errors: yes
  become: yes

- name: "Initiate Tiller Serviceaccount"
  shell: "export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf; helm init --service-account tiller"
  ignore_errors: yes
  become: yes