---
- name: Apply Weave-Network
  shell: "export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf; kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  ignore_errors: yes
  become: yes

# kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
# helm repo add stable https://kubernetes-charts.storage.googleapis.com/